//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationRRPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_profile_photo
    {
        public int User_profile_photoId { get; set; }
        public string UserId { get; set; }
        public string PhotoPath { get; set; }
        public Nullable<int> ProfilePhotoId { get; set; }
    }
}
