//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationRRPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_personal_info
    {
        public int idUser_personal_info { get; set; }
        public string UserId { get; set; }
        public string PersonalEmail { get; set; }
        public System.DateTime AdmissionDate { get; set; }
        public string EmployerNumber { get; set; }
        public Nullable<int> IdClient { get; set; }
        public string ManagerNameId { get; set; }
        public Nullable<byte> IsManager { get; set; }
    }
}
